name = "examplemod"
version = "1.0.0"
target = "javascript"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[javascript]
# Generate TypeScript .d.ts files
typescript_declarations = true

[dependencies]
gleam_stdlib = ">= 0.37.0 and < 1.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
glance = "~> 0.8.1"
simplifile = ">= 1.7.0 and < 2.0.0"
glance_printer = {path = "C:\\Users\\Jason\\Documents\\code\\4-20-24\\glance_printer"}

[dev-dependencies]
